# Generated by Django 5.1.2 on 2024-10-08 23:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('model_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)])),
                ('engine', models.CharField(max_length=30)),
                ('fuel_type', models.CharField(max_length=20)),
                ('odometer', models.IntegerField()),
                ('image', models.ImageField(blank=True, default='car_images/default.png', null=True, upload_to='car_images/')),
            ],
        ),
    ]
